guid:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
deviceid: 4065204043
ip: 0
ipstr: ""
configured: false
services:
    ssh: false
    ftp: false
    telnet: false
    rdp: false
    smb: false
