c2: mrbeef.local
ip_str: 192.168.8.100
hostname: ""
nic_vendor: ""
mac: ""
configured: false
port: 8000
device_id: 3535399484
device_key: ""
services:
    ssh: true
    ftp: false
    telnet: false
    http: false
    https: false
    smb: true
