c2: 192.168.8.101
ip_str: 172.30.211.52
hostname: AmarErFlot
nic_vendor: intel
mac: ""
configured: false
port: 8000
device_id: 1013264630
device_key: XxPFUhQ8R7kKhpgubt7v
services:
    ssh: false
    ftp: true
    telnet: false
    http: false
    https: false
    smb: false
